# Generated by Django 5.2.17 on 2026-08-06 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('gmail_address', models.EmailField(help_text='The mailbox that was searched.', max_length=254)),
                ('sender_email', models.CharField(help_text="The 'From' address (or name) that was searched for.", max_length=255)),
                ('mailbox', models.CharField(default='INBOX', max_length=120)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('succeeded', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Search queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CachedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, default='', max_length=998)),
                ('subject', models.CharField(blank=True, default='(no subject)', max_length=998)),
                ('from_address', models.CharField(blank=True, default='', max_length=998)),
                ('to_address', models.CharField(blank=True, default='', max_length=998)),
                ('date_header', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('snippet', models.CharField(blank=True, default='', max_length=280)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachment_names', models.TextField(blank=True, default='')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='fetcher.searchquery')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
    ]
